apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-qqyl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-qqyl
    app.kubernetes.io/part-of: test-app-vfcm
  name: devfile-sample-python-basic-qqyl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-qqyl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-qqyl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-txja-tenant/test-app-vfcm/devfile-sample-python-basic-qqyl@sha256:ff2f4794d6e294807abb2a914c36ed2e229b939cf869df5dc17d55d78a307d31
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
